openapi: 3.0.0
info:
  title: TDE TASKS API - Java com Springboot 
  version: 1.0.0
  description: >
    Esta API foi criada utilizando Java com o framework Spring Boot, proporcionando uma arquitetura robusta e escalável. 
    O banco de dados H2 foi escolhido por ser leve e ideal para desenvolvimento e testes rápidos, facilitando a manipulação de dados temporários. 
    O projeto visa gerenciar tarefas, permitindo a criação, atualização, deleção e marcação de tarefas como concluídas. 
    Para mais detalhes e para acessar o código-fonte completo, visite o repositório no GitHub: 
    [tde-api-tasks](https://github.com/MarcoBosc/tde-api-tasks).
tags:
  - name: Tasks
    description: Gerencie suas tarefas
paths:
  /tasks:
    get:
      tags:
        - Tasks
      summary: Retrieve all tasks
      responses:
        '200':
          description: Successful operation
    post:
      tags:
        - Tasks
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
                dataCriacao:
                  type: string
                  format: date-time
                dataLimite:
                  type: string
                  format: date-time
                finalizada:
                  type: boolean
      responses:
        '200':
          description: Successful operation
  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - Tasks
      summary: Update an existing task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
                dataCriacao:
                  type: string
                  format: date-time
                dataLimite:
                  type: string
                  format: date-time
                finalizada:
                  type: boolean
      responses:
        '200':
          description: Successful operation
    delete:
      tags:
        - Tasks
      summary: Delete a task
      responses:
        '200':
          description: Successful operation
  /tasks/{taskId}/done:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
    put:
      tags:
        - Tasks
      summary: Mark a task as done
      responses:
        '200':
          description: Successful operation
